image: ubuntu:16.04

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - code_quality
  - purge_cache


build:
  stage: build
  script:
    - sudo apt install snapd -y
    - snap install hugo --classic # use snap packe for up to date hugo version 
    - hugo
  artifacts:
    name: "${CI_PROJECT_PATH}_${CI_JOB_STAGE}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}"
    paths:
      - public
    expire_in: 3 month

code_quality:
  image: docker:stable
  stage: code_quality
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
    paths: [gl-code-quality-report.json]


# purge cloudflare cache
purge_cache:
  stage: purge_cache
  script:
    - ./gitlab-ci/purge_cache.sh
  only:
    - master


