stages:
  - pages
  - purge_cache


pages:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  image: registry.gitlab.com/pages/hugo:latest
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master


# purge cloudflare cache
purge_cache:
  image: appropriate/curl:latest
  stage: purge_cache
  script:
    - sh gitlab-ci/purge_cache.sh
  only:
    - master


