image: dettmering/hugo-build


variables:
  GIT_SUBMODULE_STRATEGY: recursive


pages:
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
  
test:
  script:
  - hugo
  except:
  - master
