stages:
  - build

before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive

build:
  stage: build
  image: registry.gitlab.com/pages/hugo:latest
  script:
    - hugo
  artifacts:
    paths:
    - public
  only:
  - master




