baseURL = "https://bn4t.me/"
languageCode = "en-us"
title = "bn4t.me"
name = "bn4t"
theme = "b3rmit"
pygmentsCodefences  = true
pygmentsUseClasses = true
enableEmoji = true # Shorthand emojis in content files - https://gohugo.io/functions/emojify/
enableRobotsTXT = true

[author]
  name = "bn4t"


[blackfriday]
  hrefTargetBlank = true


[taxonomies]
  tag = "tags"

[params]
  homeSubtitle = "A personal website"
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  # Social Icons

  [[params.social]] 
    name = "git" 
    url = "https://git.bn4t.me/bn4t"

  [[params.social]]
    name = "github"
    url = "https://github.com/bn4t"

  [[params.social]]
    name = "activitypub"
    url = "https://social.cyberpunks.xyz/@bn4t"

  [[params.social]]
    name = "matrix-org"
    url = "https://matrix.to/#/@bn4t:matrix.bn4t.me"

  [[params.social]]
    name = "envelope-o"
    url = "mailto:me@bn4t.me"


[menu]
  [[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 1
  
  [[menu.main]]
    name = "Projects"
    url = "/projects"
    weight = 2
    
    
  [[menu.main]]
    name = "Services"
    url = "/services/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 4
