baseURL = "https://bn4t.me/"
languageCode = "en-us"
title = "bn4t"
theme = "minimal"

[params]
    author = "bn4t"
    description = "Personal website by me"
    githubUsername = "bn4t"
    accent = "#444"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:info@apply55gx.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://gitlab.com/bn4t/"
    name = "gitlab"
    weight = 2

[[menu.icon]]
    url = "https://github.com/bn4t/"
    name = "github"
    weight = 3

[[menu.icon]]
    url = "https://twitter.com/_bn4t/"
    name = "twitter"
    weight = 4

[[menu.icon]]
    url = "https://www.stackoverflow.com/users/8392636/bn4t"
    name = "stack-overflow"
    weight = 5

[[menu.icon]]
    url = "http://bgfatksyqhuobs6zy6p4yvxbyltyydplrrohfavrp3vf5dltf7khb5id.onion/"
    name = "eye-slash"
    weight = 6
    
    
